### PR TITLE
Added toggleReceipts(boolean) method to prevent the default message display in-game.

### PR DESCRIPTION
**Pull request by krinsdeath**
Got kind of tired of the message (I wanted to handle it myself), so I added this method. Bumped version to 3.1.

### CODE REVIEW

**Comment by fernferret** [comment]
Nice. Will look at tonight. Would like to see if we're up to date with all the recent payment systems also, so if we have to do an allpay update, we can do it globally.

**Comment by fernferret** [comment]
Also, this will fix #9.

**Comment by krinsdeath** [comment]
I'd also like to refactor `pay()` to `take()`. `give()` and `take()` are better names, imo.

`pay()` is sort of ambiguous with its current implementation (you'd expect to be 'paying' the user specified, not taking money away).

However, I'd also like to see a `transfer()` (internal resolution of `hasEnough()` for both players + deducting with one method) if possible. I'll talk to you on IRC about it. 8-)

**Comment by krinsdeath** [comment]
Apparently my git config got messed up so it removed my global settings when I committed my new changes. Wasn't able to fix it without a merge. :[

**Comment by fernferret** [comment]
heh I'll rebase when I pull into the master branch, thanks. I'll seriously do this tonight

**Comment by fernferret** [comment]
Pulled in eefd057bbc2df841323048c3816f9bd8a572bece Thanks!

**Pull request closed without merging**
